language: python

# Run jobs on container-based infrastructure, can be overridden per job

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: linux
      language: generic  # No need to set Python version since its conda
      env: PYTHON_VER=3.7

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

    # Create test environment for package
  - python devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VER conda-envs/mols.yaml
    # Activate the test environment
  - conda activate mols_test
    # Build and install package
  - python setup.py develop --no-deps


script:
  - python setup.py test

# notifications:
#   slack:
#     if: branch = master
#     rooms:
#       - hjklol:tIyrsTGNRmimRH5PcbzOVpvO
