package:
        name: molsimplify
        version: "1.6.0"
source:
        git_url: https://github.com/hjkgrp/molSimplify.git
        git_tag: master
build:
        number: 1
        preserve_egg_dir: True
        entry_points:
                - molsimplify = molSimplify.__main__:main
requirements:
        build:
                - python
                - setuptools
                - pytest-runner
                - pyyaml
        run:
                - python
                - pyyaml
                - openbabel
                - numpy
                - scipy
                - scikit-learn
                - pyqt
                - tensorflow
about:
        home: https://github.com/hjkgrp/molSimplify
        license: BSD
        summary: "An open source toolkit for discovery of inorganic complexes"
