channels:
     - hjkgroup
     - schrodinger
     - conda-forge
     - anaconda
     - defaults
dependencies:
     - openbabel
     - numpy
     - scikit-learn
     - keras
     - beautifulsoup4
     - pandas
     - pymol
