name: Linter

on: [push, pull_request]

jobs:
  flake8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run flake8 for critical errors
      run: |
        # Fail the build for the following critical errors:
        # E9** syntax, io, or indentation error
        # F63* syntax error in assertion, comparison, or print
        # F7** syntax error in loops or functions
        # F82* undefined variables
        # Currently still excluding Informatics as there are syntax errors in that folder!
        flake8 molSimplify --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=Informatics
    - name: Run full flake8 linter
      run: |
        # Will never fail the build because of the --exit-zero flag but gives a report of the "code quality"
        flake8 molSimplify --count --statistics --max-complexity 15 --max-line-length=127 --exit-zero

    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{https://hooks.slack.com/services/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}}
