on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: action
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/chenruduan/molSimplify/blob/master/molSimplify/icons/icon.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: Post Title
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
